/**
 * @role Parent feature
 * This feature will serve as a entry point to the application
 * once the user has logged in.
 * All configuration settings for this feature will be declared here
 */
const defaultData =  {
    name: 'participants',
    singularName: 'participant',
    columns: [
        { name: "_id", sortable: false, omit: true, dataForm: false },
        { name: "order_number", sortable: true, omit: false, dataForm: false },
        { name: "name", sortable: true, omit: false, dataForm: true, dataFormPageNumber: 1, },
        { name: "email", sortable: true, omit: false, dataForm: true, dataFormPageNumber: 1, },
        { name: "division", sortable: true, omit: false, dataForm: false, },
        { name: "performance_time", sortable: true, omit: false, dataForm: false, },
        { name: "street", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 2 },
        { name: "city", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 2 },
        { name: "state", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 2 },
        { name: "zipcode", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 2 },
        { name: "band_director_name", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "band_director_phone", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "band_director_email", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "booster_parent_name", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "booster_parent_phone", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "booster_parent_email", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "parade_march_title", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "parade_march_composer", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "additional_band_staff_names", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 3 },
        { name: "drum_major", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "drum_major_name", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "color_guard_advisor", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "color_guard_captains", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "drill_team", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "drill_team_advisor", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "drill_team_captains", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "school_enrollment", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 4 },
        { name: "number_of_students_in_band", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "number_of_students_in_color_guard", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "number_of_students_in_drill_team", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "number_of_buses", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "number_of_box_trucks", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "number_of_trailers", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "number_of_tractor_trailer_rigs", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "special_instructions", sortable: false, omit: true, dataForm: true, dataFormPageNumber: 5 },
        { name: "event", sortable: false, omit: true, dataForm: false },
    ],
    defaultData: {
        _id: "",
        name: "",
        email: "",
        order_number: 0,
        division: "",
        performance_time: "",
        street: "",
        city: "",
        state: "",
        zipcode: "",
        band_director_name: "",
        band_director_phone: "",
        band_director_email: "",
        booster_parent_name: "",
        booster_parent_phone: "",
        booster_parent_email: "",
        parade_march_title: "",
        parade_march_composer: "",
        additional_band_staff_names: "",
        drum_major: "",
        drum_major_name: "",
        color_guard_advisor: "",
        color_guard_captains: "",
        drill_team: "",
        drill_team_advisor: "",
        drill_team_captains: "",
        school_enrollment: "",
        number_of_students_in_band: "",
        number_of_students_in_color_guard: "",
        number_of_students_in_drill_team: "",
        number_of_buses: "",
        number_of_box_trucks: "",
        number_of_trailers: "",
        number_of_tractor_trailer_rigs: "",
        special_instructions: "",
        event: "",
    },
    redirectComponent: "participants",
    parentFeature: "events",
    sideBarNav: true,
    formInputs: [{name: 'name', type: "text", options: []}, {name: 'email', type: "email", options: []}, {name: 'division', type: "select", options: ["Host", "A", "B", "C", "AA"]}, {name: 'performance_time', type: "time", options: []}],
    updateFormInputs: [{name: 'order_number', type: "select", options: ["None"]}, {name: 'name', type: "text", options: []}, {name: 'email', type: "email", options: []}, {name: 'division', type: "select", options: ["Host", "A", "B", "C", "AA"]}, {name: 'performance_time', type: "time", options: []}],
    orderedList: true, // Ordered lists require an "order_number" column in the columns array above
    dataForm: true,
    formPageTitles: [{name: "Participant", number: 1}, {name: "Address", number: 2}, {name: "Band Info", number: 3}, {name: "Band Info", number: 4}, {name: "Band Info", number: 5}],
}

export default defaultData;